# Generated by Django 3.0.7 on 2021-09-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(choices=[('form-one', 'form-one'), ('form-two', 'form-two'), ('form-three', 'form-three'), ('form-four', 'form-four')], default='form-one', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='student_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='class_name',
            field=models.CharField(choices=[('form-one', 'form-one'), ('form-two', 'form-two'), ('form-three', 'form-three'), ('form-four', 'form-four')], default='form-one', max_length=10),
        ),
        migrations.DeleteModel(
            name='FeedBackStaffs',
        ),
        migrations.DeleteModel(
            name='FeedBackStudent',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
    ]
