# Generated by Django 3.2.7 on 2021-09-28 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20210928_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='class_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
